title: SoloDevelopment
description: A community for solo game developers
url: "https://solodevelopment.org"
baseurl: ""

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/